server:
  servlet:
    port: 2000
    contextPath: /api


spring:
  application:
    name: proman-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/promanj
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_medatada_defaults: false
    database-plateform: org.hibernate.dialect.PostgreSQL9Dialect